import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { RequestHandler } from './$types';
import { buildReliabilityReport } from '$lib/server/report';

const PAGE_MARGIN = 42;
const HEADER_COLOR = rgb(0.1, 0.23, 0.52);
const MUTED = rgb(0.35, 0.38, 0.44);
const BODY = rgb(0.12, 0.12, 0.13);

function shortPipeline(value: string) {
	if (value === 'no_context') return 'No Context';
	if (value === 'full_context') return 'Full Context';
	if (value === 'rag') return 'RAG';
	return value;
}

export const GET: RequestHandler = async () => {
	try {
		const report = await buildReliabilityReport();

		const pdf = await PDFDocument.create();
		const page = pdf.addPage([842, 595]);
		const { width, height } = page.getSize();
		const font = await pdf.embedFont(StandardFonts.Helvetica);
		const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

		let y = height - PAGE_MARGIN;

		page.drawRectangle({
			x: 0,
			y: height - 86,
			width,
			height: 86,
			color: rgb(0.94, 0.96, 1)
		});

		page.drawText('Document Reliability Analytics Report', {
			x: PAGE_MARGIN,
			y: y - 8,
			size: 20,
			font: fontBold,
			color: HEADER_COLOR
		});
		page.drawText(`Generated: ${new Date(report.generatedAt).toLocaleString()}`, {
			x: PAGE_MARGIN,
			y: y - 30,
			size: 10,
			font,
			color: MUTED
		});

		y -= 64;

		const cardWidth = (width - PAGE_MARGIN * 2 - 24) / 4;
		const stats = [
			{ label: 'Total Runs', value: String(report.totalRuns) },
			{ label: 'Unique Queries', value: String(report.totalQueries) },
			{ label: 'Sessions', value: String(report.totalSessions) },
			{
				label: 'Avg Confidence',
				value:
					report.summary.length > 0
						? `${Math.round(report.summary.reduce((sum, item) => sum + item.avgConfidence, 0) / report.summary.length)}%`
						: '0%'
			}
		];

		for (let index = 0; index < stats.length; index += 1) {
			const x = PAGE_MARGIN + index * (cardWidth + 8);
			page.drawRectangle({
				x,
				y: y - 54,
				width: cardWidth,
				height: 48,
				color: rgb(0.97, 0.98, 0.99),
				borderColor: rgb(0.82, 0.86, 0.92),
				borderWidth: 1
			});
			page.drawText(stats[index].label, {
				x: x + 10,
				y: y - 22,
				size: 9,
				font,
				color: MUTED
			});
			page.drawText(stats[index].value, {
				x: x + 10,
				y: y - 40,
				size: 16,
				font: fontBold,
				color: BODY
			});
		}

		y -= 76;

		page.drawText('Pipeline Summary', {
			x: PAGE_MARGIN,
			y,
			size: 13,
			font: fontBold,
			color: BODY
		});
		y -= 18;

		const headers = ['Pipeline', 'Runs', 'Avg Conf', 'Avg Hall', 'Avg Latency'];
		const cols = [
			PAGE_MARGIN,
			PAGE_MARGIN + 170,
			PAGE_MARGIN + 250,
			PAGE_MARGIN + 360,
			PAGE_MARGIN + 470
		];

		for (let i = 0; i < headers.length; i += 1) {
			page.drawText(headers[i], {
				x: cols[i],
				y,
				size: 9,
				font: fontBold,
				color: MUTED
			});
		}

		y -= 12;
		page.drawLine({
			start: { x: PAGE_MARGIN, y },
			end: { x: width - PAGE_MARGIN, y },
			thickness: 1,
			color: rgb(0.85, 0.88, 0.92)
		});
		y -= 14;

		for (const item of report.summary.slice(0, 8)) {
			page.drawText(shortPipeline(item.pipeline), { x: cols[0], y, size: 10, font, color: BODY });
			page.drawText(String(item.runs), { x: cols[1], y, size: 10, font, color: BODY });
			page.drawText(`${item.avgConfidence}%`, { x: cols[2], y, size: 10, font, color: BODY });
			page.drawText(String(item.avgHallucinations), { x: cols[3], y, size: 10, font, color: BODY });
			page.drawText(`${item.avgLatencyMs} ms`, { x: cols[4], y, size: 10, font, color: BODY });
			y -= 16;
		}

		y -= 6;
		page.drawText('Recent Runs', {
			x: PAGE_MARGIN,
			y,
			size: 13,
			font: fontBold,
			color: BODY
		});
		y -= 18;

		for (const run of report.recentRuns.slice(0, 14)) {
			const text = `${new Date(run.createdAt).toLocaleDateString()} | ${shortPipeline(run.pipeline)} | ${run.modelFamily} | conf ${run.confidence}% | hall ${run.hallucinationCount} | ${run.session}`;
			page.drawText(text.slice(0, 130), { x: PAGE_MARGIN, y, size: 8.6, font, color: BODY });
			y -= 12;
			if (y < 42) break;
		}

		page.drawText('Generated by ContextLimit2', {
			x: PAGE_MARGIN,
			y: 22,
			size: 9,
			font,
			color: MUTED
		});

		const bytes = await pdf.save();
		const body = new Uint8Array(bytes);

		return new Response(body, {
			headers: {
				'Content-Type': 'application/pdf',
				'Content-Disposition': `attachment; filename="reliability-report-${Date.now()}.pdf"`
			}
		});
	} catch (error) {
		const message = error instanceof Error ? error.message : 'Failed to build PDF report.';
		return new Response(message, { status: 500 });
	}
};
